openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0.1

paths:

  ######################### Solana - API #########################

  /v0.1/tokens/{tokenAddress}:
    get:
      tags:
        - token-controller
      description: "Returns Token by address"
      operationId: getTokenByAddress
      parameters:
        - name: "tokenAddress"
          in: path
          required: true
          description: "Token address in base58"
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        '404':
          $ref: "#/components/responses/EntityNotFound"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"

  /v0.1/balance/{accountAddress}:
    get:
      tags:
        - balance-controller
      description: "Returns balance by account address"
      operationId: getBalanceByAccount
      parameters:
        - name: "accountAddress"
          in: path
          required: true
          description: "Account address in base58"
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Balance"
        '404':
          $ref: "#/components/responses/EntityNotFound"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    #################### Solana - Model ####################
    Token:
      type: object
      properties:
        address:
          type: string
        supply:
          $ref: "#/components/schemas/BigInteger"
        collection:
          type: string
      required:
        - address
        - supply

    Balance:
      required:
        - account
        - value
      type: object
      properties:
        account:
          type: string
          description: Account address in base58
        value:
          "$ref": "#/components/schemas/BigInteger"

    #################### Solana - Events ####################
    TokenEvent:
      required:
        - eventId
        - address
      properties:
        eventId:
          type: string
        address:
          type: string
      oneOf:
        - $ref: "#/components/schemas/TokenUpdateEvent"
        - $ref: "#/components/schemas/TokenDeleteEvent"
    TokenUpdateEvent:
      type: object
      required:
        - token
      properties:
        type:
          type: string
          enum:
            - UPDATE
        token:
          $ref: "#/components/schemas/Token"
    TokenDeleteEvent:
      type: object
      required:
        - address
      properties:
        type:
          type: string
          enum:
            - DELETE

    BalanceEvent:
      required:
        - eventId
        - account
      properties:
        eventId:
          type: string
        account:
          description: Account address in base58
          type: string
      oneOf:
        - $ref: "#/components/schemas/BalanceUpdateEvent"
    BalanceUpdateEvent:
      type: object
      required:
        - balance
      properties:
        type:
          type: string
          enum:
            - UPDATE
        balance:
          $ref: "#/components/schemas/Balance"
    #################### Solana - Errors ####################

    SolanaApiErrorEntityNotFound:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          enum:
            - NOT_FOUND
          default: NOT_FOUND
        message:
          type: string
          description: "Error message"

    SolanaApiErrorBadRequest:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          enum:
            - BAD_REQUEST
            - VALIDATION
          default: BAD_REQUEST
        message:
          type: string
          description: "Error message"

    SolanaApiErrorServerError:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          enum:
            - UNKNOWN
          default: UNKNOWN
        message:
          type: string
          description: "Error message"

    #################### Referenced Types ####################

    BigInteger:
      type: string
      example: 123456
    BigDecimal:
      type: string
      example: 123456.789


  #======================== Responses ============================#

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/SolanaApiErrorBadRequest"
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/SolanaApiErrorServerError"
    EntityNotFound:
      description: Not Found
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/SolanaApiErrorEntityNotFound"
